using Game.General.Properties;
using System.Collections.Generic;
using UnityEngine;

namespace Game.Ctrller.Map
{
    public sealed class MapDiagram
    {
        private MapDiagramNode[,] _nodes;

        // general getters
        public MapDiagramNode this[int x, int y]
        {
            get => _nodes[x, y];
        }
        public IEnumerable<MapDiagramNode> Content
        {
            get
            {
                for (int i = 0; i < _nodes.GetLength(0); i++)
                    for (int j = 0; j < _nodes.GetLength(1); j++)
                        yield return _nodes[i, j];
            }
        }

        // properties
        public int SizeX => _nodes.GetLength(0);
        public int SizeY => _nodes.GetLength(1);
        public int TotalNodeNum => SizeX * SizeY;
        /// <summary>
        /// number of node that closed, which are not <br/>
        /// connected to other area.
        /// </summary>
        /// <remarks>
        /// theoretically, the diagram-generator-progrom  <br/>
        /// will not produce such area. but it still may  <br/>
        /// generated by other program, such as structure <br/>
        /// generator etc.
        /// </remarks>
        public int ClosedNodeNum { get; set; } = 0;
        public Coord CenterPoint => new(SizeX / 2, SizeY / 2);

        // readonly properties
        private readonly MapBasicProperty _basicProperty;

        /*
         *  constructors
         *  
         *  methods that used to init the diagram.
         */

        public MapDiagram(MapBasicProperty basicProperty)
        {
            _basicProperty = basicProperty;

            InitMapAsMatrix();
        }       
        private void InitMapAsMatrix()
        {
            _nodes = new MapDiagramNode[_basicProperty.Size_X, _basicProperty.Size_Y];

            // arrage
            for (int i = 0; i < this.SizeX; i++)
            {
                for (int j = 0; j < this.SizeY; j++)
                {
                    _nodes[i, j] = new();
                    _nodes[i, j].Coordinate = new(i, j);
                }
            }
        }

        /*
         *  core functions
         *  
         *  methods that carry the core function in diagram,
         *  which play important effects on map algorithm.
         */

        /// <summary>
        /// calculate if the input coordinate can place <br/>
        /// an obstacle with no influence on acccessible.
        /// </summary>
        /// <param name="targetCoord">coordinate to judge</param>
        /// <returns>true if input coordinate is placeable.</returns>
        public bool JudgeIfCanPlaceObstacle(Coord targetCoord)
        {
            // Summary: 

            // This function will do following things to calculate:

            // First, it made an assumption that [targetCoord] IS 
            // an obstacle, and mark the center point of the map as
            // the program [beginning point].

            // Then, begin on the [begining point], program will
            // startup an ergodic for all tiles in the map, with
            // counting the number of accessible tile.

            // After the ergodic, program compares the truly number
            // of accessible tile with the numbers of it should be
            // (provides by map properties, calculate by total map
            // tile number and obstacle percentage.)

            // If those 2 numbers are equals, our assumption is
            // hold. which means, we can indeed do put an obstacle
            // without any accessible problem.

            // In that case, function will return TRUE.

            if (JudgeCoordIfOutOfRange(targetCoord))
                return false;

            # region Properties Define

            // storage current data as template.
            // by this, program can execute without modify actual data.
            var currentObsExistMap = GetObstacleDiagram();
            int currentObsNum = GetCurrentObstacleNum();
           
            // count of accessible tile.
            // by compare this value with ideal count, we can get the result.
            int accessibleTileCount = 0;

            // sign checked coord.
            bool[,] mapCheckedFlags = new bool[this.SizeX, this.SizeY];
            Queue<Coord> checkedCoords = new();

            #endregion

            #region Program

            // init, mark center point as accessible and start
            SignCoordAsAccessible(this.CenterPoint);

            // posit current input coord is obstacle.
            PositCurrentTileIsObs();

            // check every point in the map.
            // for each point, check accessiblely of its neighbor(x+-1, y+-1).
            while (checkedCoords.Count > 0)
            {
                var currentTileCoord = checkedCoords.Dequeue();

                for (int x = -1; x <= 1; x++)
                {
                    for (int y = -1; y <= 1; y++)
                    {
                        Coord neighbor = new(
                            currentTileCoord.x + x,
                            currentTileCoord.y + y
                        );

                        if ((x != 0 && y != 0) || JudgeCoordIfOutOfRange(neighbor))
                            continue;

                        if (mapCheckedFlags[neighbor.x, neighbor.y] || currentObsExistMap[neighbor.x, neighbor.y])
                            continue;

                        SignCoordAsAccessible(neighbor);
                    }
                }
            }

            // calculate if the assumption holds, return the result.
            return CalculateAccessible();

            #endregion

            #region Local Functions

            // process func
            void PositCurrentTileIsObs()
            {
                currentObsExistMap[targetCoord.x, targetCoord.y] = true;
                currentObsNum++;
            }
            void SignCoordAsAccessible(Coord target)
            {
                mapCheckedFlags[target.x, target.y] = true;
                accessibleTileCount++;
                checkedCoords.Enqueue(target);
            }
            
            // temp property getter
            int GetCurrentObstacleNum()
            {
                int num = 0;

                foreach (var node in this.Content)
                    if (node.IsObstacle)
                        num++;

                return num;
            }
            bool[,] GetObstacleDiagram()
            {
                bool[,] diagram = new bool[this.SizeX, this.SizeY];

                foreach (var node in this.Content)
                    if (node.IsObstacle)
                        diagram[node.Coordinate.x, node.Coordinate.y] = true;

                return diagram;
            }

            // result calculator
            bool CalculateAccessible()
            {
                // get ideal
                int idealAccessibleCount = this.TotalNodeNum - this.ClosedNodeNum - currentObsNum;
                return accessibleTileCount == idealAccessibleCount;
            }

            #endregion
        }

        /// <summary>
        /// judge if given coorinate is out of diagram node array's length.
        /// </summary>
        /// <param name="targetCoord"></param>
        /// <returns><see langword="true"/> if out of range.</returns>
        public bool JudgeCoordIfOutOfRange(Coord targetCoord)
        {
            return (targetCoord.x < 0 || targetCoord.x >= this.SizeX)
                   ||
                   (targetCoord.y < 0 || targetCoord.y >= this.SizeY);
        }

        /// <summary>
        /// print debug info as unicode graph on console.
        /// </summary>
        public void PrintDebugGraph()
        {
            string msg = "";

            for (int x = 0; x < this.SizeX; x++)
            {
                for (int y = 0; y < this.SizeY; y++)
                {
                    var node = GetTransformedValue(_nodes, x, y);
                    msg += (GetGridOutputMsg(node.IsObstacle) + " ");
                }
                msg += "\n";
            }
            Debug.Log("地形示意图(z ↑ x →): \n" + msg);

            /*
             *  functions
             */

            static T GetTransformedValue<T>(T[,] origMartix, int x, int y)
            {
                var transed_x = y;
                var transed_y = origMartix.GetLength(0) - x - 1;
                return origMartix[transed_x, transed_y];
            }
            static string GetGridOutputMsg(bool isObs)
            {
                return isObs ? "■" : "□";
            }
        }
        
    }
}
